trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: tharani
  imageName: train
  pswd: Mkk7KdF6vSKS6=KWib=pdfqlOgeJ0Gb1

steps:
- script: |
    docker build -t $(dockerId).azurecr.io/$(imageName) .
    docker login -u $(dockerId) -p $(pswd) $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)
  displayName: Build and Pushing the Image

- bash: find resource-manifests -type f -name "*.yaml" -print0 | 
      xargs -0 sed -i -e "s/{{TAG}}/$(build.buildId)/" \   
      -e "s/{{DOCKER_USER}}/$(dockerId)/"


- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/resource-manifests'
    artifactName: resource-manifests
  displayName: Publish yaml
    
