trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: tharani
  imageName: train

steps:
- script: |
    docker build -t $(dockerId).azurecr.io/$(imageName) .
    docker login -u $(dockerId) -p $(pswd) $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)
  env:
    pswd: Mkk7KdF6vSKS6=KWib=pdfqlOgeJ0Gb1
